version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Entered the build phase ...
      #Lambda deploy reference
      #https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-deploying.html
      #Build spec reference
      #https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
      # Package SAM template
      - sam package --template-file template.yaml --s3-bucket mysambucketforhelloworld --output-template-file packaged.yaml
      # Deploy packaged SAM template
      - sam deploy --template-file packaged.yaml --region us-east-2 --stack-name my-sam-app --capabilities CAPABILITY_NAMED_IAM --no-confirm-changeset 
