version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Entered the build phase ...
      #Lambda deploy reference
      #https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-deploying.html
      #Build spec reference
      #https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
      # Package SAM template
      - sam build && sam package --template pwd\.aws-sam\build\template.yaml --s3-bucket mysambucketforhelloworld --output-template-file outputTemplate.yaml 
      
artifacts:
  files:
    - template.yaml
    - outputTemplate.yaml      
      

      
